// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type HomeViewModel struct {
	PossiblePairCount int
}

func HomePage(vm HomeViewModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"relative flex flex-col items-center justify-center min-h-screen gap-5\"><div class=\"absolute flex top-0 right-0 z-10\"><a href=\"/docs\" class=\"inline-block p-4\" title=\"Documentation and help\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = DocsIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</a> <a href=\"/buckets\" class=\"inline-block p-4\" title=\"Buckets\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = BucketsIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</a> <a href=\"/stats\" class=\"inline-block p-4\" title=\"Stats\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = StatsIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</a><div class=\"js-drawer-open p-4 cursor-pointer\" title=\"Configuration\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ConfigIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div><h1 class=\"text-3xl\">Generate a server name</h1><div id=\"generate-name-container\" class=\"w-full flex justify-center\"><span class=\"text-gray-400\">The name will be here</span></div><button hx-get=\"/generate\" hx-target=\"#generate-name-container\" hx-include=\".js-generate-configuration\" class=\"cursor-pointer rounded-full border-2 border-primary bg-primary text-white px-8 py-3 text-sm font-medium hover:bg-primary-600 focus:outline-none focus:ring active:text-opacity-75\" type=\"button\">Generate</button></div><div id=\"drawer\" class=\"fixed top-0 right-0 z-20 w-60 h-screen p-4 bg-white overflow-y-auto transition-transform translate-x-full opacity-0 shadow-xl\" tabindex=\"-1\" aria-hiden=\"true\"><div class=\"relative flex flex-col w-full h-full\"><button type=\"button\" class=\"js-drawer-close text-gray-400 bg-transparent hover:bg-slate-300 hover:text-gray-900 rounded-lg cursor-pointer text-sm w-6 h-6 absolute top-0 end-0 flex items-center justify-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = CloseIcon().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span class=\"sr-only\">Close menu</span></button><div class=\"text-xl font-semibold\">Configuration</div><div class=\"js-generate-configuration mt-4 flex flex-col gap-4\" hx-get=\"/config/stats\" hx-trigger=\"change delay:100ms\" hx-include=\"this\" hx-target=\".js-config-stats\"><div class=\"flex flex-col gap-2\"><div class=\"flex gap-1 items-center\"><span class=\"text-sm font-medium text-gray-800\">Length</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Toggle(ToggleAttrs{Name: "lengthEnabled", Class: "js-config-length-toggle"}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"js-config-length-opacity opacity-40 flex flex-col gap-2\"><div><div class=\"inline-flex rounded-md shadow-sm\" role=\"group\"><label><input type=\"radio\" name=\"lengthMode\" value=\"upto\" checked=\"checked\" disabled=\"disabled\" class=\"sr-only peer js-length-linked\"><div class=\"px-2 py-1 text-xs font-medium text-slate-800 bg-white border border-secondary/20 rounded-s cursor-pointer hover:bg-secondary/10 peer-checked:bg-secondary peer-checked:text-white peer-checked:hover:bg-secondary peer-checked:hover:text-white\">Up to</div></label> <label><input type=\"radio\" name=\"lengthMode\" value=\"exactly\" disabled=\"disabled\" class=\"sr-only peer js-length-linked\"><div class=\"px-2 py-1 text-xs font-medium text-slate-800 bg-white border border-secondary/20 rounded-e cursor-pointer hover:bg-secondary/10 peer-focus:z-10 peer-checked:bg-secondary peer-checked:text-white peer-checked:hover:bg-secondary peer-checked:hover:text-white\">Exactly</div></label></div></div><div class=\"js-length-range-container\"><div class=\"flex justify-center\"><div class=\"js-length-range-value text-sm font-semibold\">14</div></div><div class=\"relative\"><input name=\"lengthValue\" type=\"range\" value=\"14\" min=\"7\" max=\"19\" disabled=\"disabled\" class=\"js-length-range-slider js-length-linked accent-secondary disabled:accent-gray-400 bg-primary w-full h-2 rounded-lg appearance-none cursor-pointer\"> <span class=\"text-sm text-gray-500 absolute start-0 -bottom-6\">7</span> <span class=\"text-sm text-gray-500 absolute start-1/2 -translate-x-1/2 rtl:translate-x-1/2 -bottom-6\">12</span> <span class=\"text-sm text-gray-500 absolute end-0 -bottom-6\">19</span></div></div></div></div><div class=\"js-config-stats pt-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ConfigurationStatsPartial(ConfigurationStatsPartialViewModel{PossiblePairCount: vm.PossiblePairCount}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
