//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// BucketDetails defines model for BucketDetails.
type BucketDetails struct {
	// ArchivedAt Timestamp when the bucket was archived
	ArchivedAt *time.Time `json:"archived_at"`

	// CreatedAt Timestamp when the bucket was created
	CreatedAt time.Time `json:"created_at"`

	// Description Description of the bucket
	Description string `json:"description"`

	// Id Unique identifier for the bucket
	Id int32 `json:"id"`

	// Name Name of the bucket
	Name string `json:"name"`

	// RemainingPairs Number of names remaining in the bucket
	RemainingPairs int64 `json:"remaining_pairs"`

	// UpdatedAt Timestamp when the bucket was last updated
	UpdatedAt *time.Time `json:"updated_at"`
}

// BucketListItem defines model for BucketListItem.
type BucketListItem struct {
	// ArchivedAt Timestamp when the bucket was archived
	ArchivedAt *time.Time `json:"archived_at"`

	// CreatedAt Timestamp when the bucket was created
	CreatedAt time.Time `json:"created_at"`

	// Description Description of the bucket
	Description string `json:"description"`

	// Id Unique identifier for the bucket
	Id int32 `json:"id"`

	// Name Name of the bucket
	Name string `json:"name"`

	// UpdatedAt Timestamp when the bucket was last updated
	UpdatedAt *time.Time `json:"updated_at"`
}

// Error defines model for Error.
type Error struct {
	// InternalErrorMessage Internal error message (only in debug mode)
	InternalErrorMessage *string `json:"internal.error.message,omitempty"`

	// InternalErrorType Internal error type (only in debug mode)
	InternalErrorType *string `json:"internal.error.type,omitempty"`

	// Title Error title
	Title string `json:"title"`
}

// ProblemDetail RFC 7807 Problem Details for HTTP APIs
type ProblemDetail struct {
	// Detail A human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type
	Type string `json:"type"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// ListBucketsParams defines parameters for ListBuckets.
type ListBucketsParams struct {
	// Archived If present (regardless of value), returns only archived buckets
	Archived *string `form:"archived,omitempty" json:"archived,omitempty"`
}

// CreateBucketJSONBody defines parameters for CreateBucket.
type CreateBucketJSONBody struct {
	Filters struct {
		// Length Length constraint for generated names
		Length int `json:"length"`

		// LengthMode Mode for length constraint (e.g., exact, max, min)
		LengthMode string `json:"length_mode"`
	} `json:"filters"`

	// Name Name of the bucket
	Name string `json:"name"`
}

// CreateBucketJSONRequestBody defines body for CreateBucket for application/json ContentType.
type CreateBucketJSONRequestBody CreateBucketJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all buckets
	// (GET /v1alpha1/buckets)
	ListBuckets(w http.ResponseWriter, r *http.Request, params ListBucketsParams)
	// Create a new bucket
	// (POST /v1alpha1/buckets)
	CreateBucket(w http.ResponseWriter, r *http.Request)
	// Get bucket details
	// (GET /v1alpha1/buckets/{id})
	GetBucketDetails(w http.ResponseWriter, r *http.Request, id int32)
	// Pop a name from bucket
	// (POST /v1alpha1/buckets/{id}/pop)
	PopBucketName(w http.ResponseWriter, r *http.Request, id int32)
	// Generate a random server name
	// (POST /v1alpha1/generate)
	GenerateName(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuckets operation middleware
func (siw *ServerInterfaceWrapper) ListBuckets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBucketsParams

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameter("form", true, false, "archived", r.URL.Query(), &params.Archived)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuckets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBucket operation middleware
func (siw *ServerInterfaceWrapper) CreateBucket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBucket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBucketDetails operation middleware
func (siw *ServerInterfaceWrapper) GetBucketDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBucketDetails(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PopBucketName operation middleware
func (siw *ServerInterfaceWrapper) PopBucketName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PopBucketName(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateName operation middleware
func (siw *ServerInterfaceWrapper) GenerateName(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateName(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/v1alpha1/buckets", wrapper.ListBuckets)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/buckets", wrapper.CreateBucket)
	m.HandleFunc("GET "+options.BaseURL+"/v1alpha1/buckets/{id}", wrapper.GetBucketDetails)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/buckets/{id}/pop", wrapper.PopBucketName)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/generate", wrapper.GenerateName)

	return m
}

type InternalServerErrorJSONResponse Error

type ListBucketsRequestObject struct {
	Params ListBucketsParams
}

type ListBucketsResponseObject interface {
	VisitListBucketsResponse(w http.ResponseWriter) error
}

type ListBuckets200JSONResponse struct {
	Buckets []BucketListItem `json:"buckets"`
}

func (response ListBuckets200JSONResponse) VisitListBucketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListBuckets500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListBuckets500JSONResponse) VisitListBucketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateBucketRequestObject struct {
	Body *CreateBucketJSONRequestBody
}

type CreateBucketResponseObject interface {
	VisitCreateBucketResponse(w http.ResponseWriter) error
}

type CreateBucket201Response struct {
}

func (response CreateBucket201Response) VisitCreateBucketResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreateBucket500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateBucket500JSONResponse) VisitCreateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBucketDetailsRequestObject struct {
	Id int32 `json:"id"`
}

type GetBucketDetailsResponseObject interface {
	VisitGetBucketDetailsResponse(w http.ResponseWriter) error
}

type GetBucketDetails200JSONResponse BucketDetails

func (response GetBucketDetails200JSONResponse) VisitGetBucketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBucketDetails500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetBucketDetails500JSONResponse) VisitGetBucketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PopBucketNameRequestObject struct {
	Id int32 `json:"id"`
}

type PopBucketNameResponseObject interface {
	VisitPopBucketNameResponse(w http.ResponseWriter) error
}

type PopBucketName200JSONResponse struct {
	// Name The popped server name
	Name string `json:"name"`
}

func (response PopBucketName200JSONResponse) VisitPopBucketNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PopBucketName409JSONResponse ProblemDetail

func (response PopBucketName409JSONResponse) VisitPopBucketNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PopBucketName500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PopBucketName500JSONResponse) VisitPopBucketNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GenerateNameRequestObject struct {
}

type GenerateNameResponseObject interface {
	VisitGenerateNameResponse(w http.ResponseWriter) error
}

type GenerateName200JSONResponse struct {
	// Name The generated server name
	Name string `json:"name"`
}

func (response GenerateName200JSONResponse) VisitGenerateNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateName500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GenerateName500JSONResponse) VisitGenerateNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all buckets
	// (GET /v1alpha1/buckets)
	ListBuckets(ctx context.Context, request ListBucketsRequestObject) (ListBucketsResponseObject, error)
	// Create a new bucket
	// (POST /v1alpha1/buckets)
	CreateBucket(ctx context.Context, request CreateBucketRequestObject) (CreateBucketResponseObject, error)
	// Get bucket details
	// (GET /v1alpha1/buckets/{id})
	GetBucketDetails(ctx context.Context, request GetBucketDetailsRequestObject) (GetBucketDetailsResponseObject, error)
	// Pop a name from bucket
	// (POST /v1alpha1/buckets/{id}/pop)
	PopBucketName(ctx context.Context, request PopBucketNameRequestObject) (PopBucketNameResponseObject, error)
	// Generate a random server name
	// (POST /v1alpha1/generate)
	GenerateName(ctx context.Context, request GenerateNameRequestObject) (GenerateNameResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBuckets operation middleware
func (sh *strictHandler) ListBuckets(w http.ResponseWriter, r *http.Request, params ListBucketsParams) {
	var request ListBucketsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBuckets(ctx, request.(ListBucketsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBuckets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBucketsResponseObject); ok {
		if err := validResponse.VisitListBucketsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBucket operation middleware
func (sh *strictHandler) CreateBucket(w http.ResponseWriter, r *http.Request) {
	var request CreateBucketRequestObject

	var body CreateBucketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBucket(ctx, request.(CreateBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBucket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBucketResponseObject); ok {
		if err := validResponse.VisitCreateBucketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBucketDetails operation middleware
func (sh *strictHandler) GetBucketDetails(w http.ResponseWriter, r *http.Request, id int32) {
	var request GetBucketDetailsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBucketDetails(ctx, request.(GetBucketDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBucketDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBucketDetailsResponseObject); ok {
		if err := validResponse.VisitGetBucketDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PopBucketName operation middleware
func (sh *strictHandler) PopBucketName(w http.ResponseWriter, r *http.Request, id int32) {
	var request PopBucketNameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PopBucketName(ctx, request.(PopBucketNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PopBucketName")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PopBucketNameResponseObject); ok {
		if err := validResponse.VisitPopBucketNameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateName operation middleware
func (sh *strictHandler) GenerateName(w http.ResponseWriter, r *http.Request) {
	var request GenerateNameRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateName(ctx, request.(GenerateNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateName")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateNameResponseObject); ok {
		if err := validResponse.VisitGenerateNameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYXW/buBL9KwTvfWgv5I846W3rt6Ttdg30I0jTly2KYCyOLXYpkiUpJ0bg/74gKclW",
	"RNfbNt3FLgr0IZaomTMzZ84Me0tzVWolUTpLp7fUoNVKWgw/ZtKhkSDeoVmheWGMMv5xrqRD6fyfoLXg",
	"OTiu5OiTVdI/s3mBJfi//mtwQaf0P6Otj1F8a0fR2mazyShDmxuuvRE6bZ0SG7wSrA9mteGA7KzKf0f3",
	"HB1wER5oozQaxyNwMHnBV8iuIKDsOrjkJVoHpSbXBUriCiTzYI5cgyXNpzSjC2VKb4AycDhwvESaUVkJ",
	"AXOBdOpMhRl1a410Sq0zXC7pJqO5QXDf5Lr+kmYUb6DU3gedjCePBkeTwWRyeTSejv2/3/ZB60HpOL+L",
	"5fn2F1GLHSwd/7H0REKJliyUIdooVuXhK5QrbpQsPRcS3jnrO30v+ecKCWcoHV9wNMFm2vfRTphcuuPJ",
	"1gmXDpdovBePrO/nDZT4hai2QQwiy2wqAIMlcMnl8koDNzbhpSrnaLyfmJ/2A8LlHtcnk25U/z9JRlVp",
	"9o0kEmAdqT//ApOOv8ikAyQPuflccYOMTj/4Qtd16FKu0wv9dH5s7ar5J8ydjzv29Stu3cxh+bOxfzb2",
	"j2jsf193pXqpndfdFuL1fB2GwTos0VpYJjLdzuFwjtTnyAMlxdrrG8N5tSSlYviwkwkGDuZgkeRKSoyE",
	"WgAXIWF9LnXRxPcHoPhDh3H8Lxy20fC76DABwHEnEi5fRE/h5a7VFkrdPzHJh2oY7aSKdG7UXGAZN5k+",
	"jItfnpHHT8aPSX2O1CtP6K5fLy/Pyen5zHO8W2O2x9wpKaoS5MAgMM9AgjdagAz7G7Eac77gOXGKuIJb",
	"ovK8MgZl3k3B5bYl+FZWh+StL4i3TDyUYNOSHCSZI+HWVsgILIFL6wh3w1QtrANXJeZsCDS+JLliHTgn",
	"46cp9dhT1lNiC2VcdjcPtipLMOtGWXTMdifst01QntgLwXM3JGdtGmLcUqyTgaVpfUreX8yIwQWGJBNX",
	"gNsqqN1FEjjfgdPm+KqBc5CFdXrrY9leVm5CXy5UAvH5LDBviTJ4l0tiQDJVNst6HCcgGSlBwtIf8I9q",
	"vtjWaS3kr9dNH52ez2hGvWBHT0fD8XA8AKELOPIZVBolaE6n9Hg4Hh57xoMrAldGq6N4btR4md7SJSa0",
	"/QJdZaQlQAS3zhcbhGiwZUSFcyDEmiy4cGiQ+V6whboOpW25vhNOW4YZo1PqF5ez9p0GAyU6P4SmH3qa",
	"tiDaoEXpyAODSzBMoLUe0wpEhQ8zYmq0+1xzb+ZzhWbdDIgp3Vlyttewu6z4mHWveZPx+KuudV2t2Uk6",
	"d1jaQxe/Oyte2x0UjIF1j7SN+TRNuzl9V+U5WruoRFAiZzhuUxZq7t09iuGmMLZpGaWuvuEOGoWirvUu",
	"f7xprWyCds/CnPa0k3jdoPE9suBCWMIdueauaJoKWd1Ffoh6TWl0YMUZspqZfepFJ2fNSuRTiNadKbb+",
	"jto2znovBMqlK/qhvgrPvUJaZ4BLtysXTWSdXXCcUu9o/soP9b6P14phMCt6zh7gcDnMCN5A7jJSwk1G",
	"Si67e0EJNweVsg6vCyQ1vn/YknoHUL3/NfVIN8P2A79XbnpdftRHWg8wu9s4zW3l/lolcrPD/3Cip9yj",
	"W842B+U7bjfIiB9Sfr/2QxnmqnIEtltMm/hun7xE1/3PowM6XWdo9rxRXD93toIbtvNu4nel9+A957vF",
	"+LDUNoF+tWCy5sN7I8JLdD3je3kw0koH5UmK6gWWalXvGqad62HZWBhVht6rudBG1CPDudIxR29if/2j",
	"mdBV6LQy+d1dK62R7W5sHXWaG1jhoFSVdMDln1Omrx7ONYa7BWu0IaMn46f31gbdO1YC2rN6gyaDnY2+",
	"3bgiw4AN/CJ2j81wrnQnAUlhbEbn/kZ4WZ/w9LdcLgUmdvKEDMavauL/JcTbrgF/K/e2MGL271XfomkC",
	"qRoEYM3E7+vLK5WDIAxXKJQu/cUgnqUZrYygU1o4p6ejkfDnCmXd9Mn4yXjkb0Wbj5s/AgAA//8UbS/H",
	"yRkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
