//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for BucketDetailsFiltersLengthMode.
const (
	BucketDetailsFiltersLengthModeExactly BucketDetailsFiltersLengthMode = "exactly"
	BucketDetailsFiltersLengthModeUpto    BucketDetailsFiltersLengthMode = "upto"
)

// Defines values for CreateBucketJSONBodyFiltersLengthMode.
const (
	CreateBucketJSONBodyFiltersLengthModeExactly CreateBucketJSONBodyFiltersLengthMode = "exactly"
	CreateBucketJSONBodyFiltersLengthModeUpto    CreateBucketJSONBodyFiltersLengthMode = "upto"
)

// Defines values for GenerateNameJSONBodyFiltersLengthMode.
const (
	Exactly GenerateNameJSONBodyFiltersLengthMode = "exactly"
	Upto    GenerateNameJSONBodyFiltersLengthMode = "upto"
)

// BucketDetails defines model for BucketDetails.
type BucketDetails struct {
	// ArchivedAt Timestamp when the bucket was archived
	ArchivedAt *time.Time `json:"archived_at"`

	// CreatedAt Timestamp when the bucket was created
	CreatedAt time.Time `json:"created_at"`

	// Description Description of the bucket
	Description string `json:"description"`

	// Filters Filter configuration for this bucket
	Filters struct {
		// Length Length constraint value (null if not enabled)
		Length *int `json:"length"`

		// LengthEnabled Whether length filtering is enabled
		LengthEnabled bool `json:"length_enabled"`

		// LengthMode Mode for length constraint
		LengthMode *BucketDetailsFiltersLengthMode `json:"length_mode,omitempty"`
	} `json:"filters"`

	// Id Unique identifier for the bucket
	Id int32 `json:"id"`

	// Name Name of the bucket
	Name string `json:"name"`

	// RemainingPairs Number of names remaining in the bucket
	RemainingPairs int64 `json:"remaining_pairs"`

	// UpdatedAt Timestamp when the bucket was last updated
	UpdatedAt *time.Time `json:"updated_at"`
}

// BucketDetailsFiltersLengthMode Mode for length constraint
type BucketDetailsFiltersLengthMode string

// BucketListItem defines model for BucketListItem.
type BucketListItem struct {
	// ArchivedAt Timestamp when the bucket was archived
	ArchivedAt *time.Time `json:"archived_at"`

	// CreatedAt Timestamp when the bucket was created
	CreatedAt time.Time `json:"created_at"`

	// Description Description of the bucket
	Description string `json:"description"`

	// Id Unique identifier for the bucket
	Id int32 `json:"id"`

	// Name Name of the bucket
	Name string `json:"name"`

	// UpdatedAt Timestamp when the bucket was last updated
	UpdatedAt *time.Time `json:"updated_at"`
}

// Error defines model for Error.
type Error struct {
	// InternalErrorMessage Internal error message (only in debug mode)
	InternalErrorMessage *string `json:"internal.error.message,omitempty"`

	// InternalErrorType Internal error type (only in debug mode)
	InternalErrorType *string `json:"internal.error.type,omitempty"`

	// Title Error title
	Title string `json:"title"`
}

// ProblemDetail RFC 7807 Problem Details for HTTP APIs
type ProblemDetail struct {
	// Detail A human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type
	Type string `json:"type"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// ListBucketsParams defines parameters for ListBuckets.
type ListBucketsParams struct {
	// Archived If present (regardless of value), returns only archived buckets
	Archived *string `form:"archived,omitempty" json:"archived,omitempty"`
}

// CreateBucketJSONBody defines parameters for CreateBucket.
type CreateBucketJSONBody struct {
	// Description Description of the bucket
	Description *string `json:"description,omitempty"`

	// Filters Optional filters for name generation. If not provided, names are generated without constraints.
	Filters *struct {
		// Length Length constraint for generated names (required if length_enabled is true)
		Length *int `json:"length,omitempty"`

		// LengthEnabled Whether length filtering is enabled
		LengthEnabled *bool `json:"length_enabled,omitempty"`

		// LengthMode Mode for length constraint
		LengthMode *CreateBucketJSONBodyFiltersLengthMode `json:"length_mode,omitempty"`
	} `json:"filters,omitempty"`

	// Name Name of the bucket
	Name string `json:"name"`
}

// CreateBucketJSONBodyFiltersLengthMode defines parameters for CreateBucket.
type CreateBucketJSONBodyFiltersLengthMode string

// UpdateBucketJSONBody defines parameters for UpdateBucket.
type UpdateBucketJSONBody struct {
	// Description New description for the bucket. Use empty string to clear the description.
	Description *string `json:"description,omitempty"`
}

// GenerateNameJSONBody defines parameters for GenerateName.
type GenerateNameJSONBody struct {
	// Filters Optional filters for name generation. If not provided, names are generated without constraints.
	Filters *struct {
		// Length Length constraint for generated names (required if length_enabled is true)
		Length *int `json:"length,omitempty"`

		// LengthEnabled Whether length filtering is enabled
		LengthEnabled *bool `json:"length_enabled,omitempty"`

		// LengthMode Mode for length constraint
		LengthMode *GenerateNameJSONBodyFiltersLengthMode `json:"length_mode,omitempty"`
	} `json:"filters,omitempty"`
}

// GenerateNameJSONBodyFiltersLengthMode defines parameters for GenerateName.
type GenerateNameJSONBodyFiltersLengthMode string

// CreateBucketJSONRequestBody defines body for CreateBucket for application/json ContentType.
type CreateBucketJSONRequestBody CreateBucketJSONBody

// UpdateBucketJSONRequestBody defines body for UpdateBucket for application/json ContentType.
type UpdateBucketJSONRequestBody UpdateBucketJSONBody

// GenerateNameJSONRequestBody defines body for GenerateName for application/json ContentType.
type GenerateNameJSONRequestBody GenerateNameJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all buckets
	// (GET /v1alpha1/buckets)
	ListBuckets(w http.ResponseWriter, r *http.Request, params ListBucketsParams)
	// Create a new bucket
	// (POST /v1alpha1/buckets)
	CreateBucket(w http.ResponseWriter, r *http.Request)
	// Get bucket details
	// (GET /v1alpha1/buckets/{id})
	GetBucketDetails(w http.ResponseWriter, r *http.Request, id int32)
	// Update bucket
	// (PATCH /v1alpha1/buckets/{id})
	UpdateBucket(w http.ResponseWriter, r *http.Request, id int32)
	// Archive a bucket
	// (POST /v1alpha1/buckets/{id}/archive)
	ArchiveBucket(w http.ResponseWriter, r *http.Request, id int32)
	// Pop a name from bucket
	// (POST /v1alpha1/buckets/{id}/pop)
	PopBucketName(w http.ResponseWriter, r *http.Request, id int32)
	// Recover an archived bucket
	// (POST /v1alpha1/buckets/{id}/recover)
	RecoverBucket(w http.ResponseWriter, r *http.Request, id int32)
	// Generate a random server name
	// (POST /v1alpha1/generate)
	GenerateName(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuckets operation middleware
func (siw *ServerInterfaceWrapper) ListBuckets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBucketsParams

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameter("form", true, false, "archived", r.URL.Query(), &params.Archived)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuckets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBucket operation middleware
func (siw *ServerInterfaceWrapper) CreateBucket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBucket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBucketDetails operation middleware
func (siw *ServerInterfaceWrapper) GetBucketDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBucketDetails(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBucket operation middleware
func (siw *ServerInterfaceWrapper) UpdateBucket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBucket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveBucket operation middleware
func (siw *ServerInterfaceWrapper) ArchiveBucket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveBucket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PopBucketName operation middleware
func (siw *ServerInterfaceWrapper) PopBucketName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PopBucketName(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecoverBucket operation middleware
func (siw *ServerInterfaceWrapper) RecoverBucket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecoverBucket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateName operation middleware
func (siw *ServerInterfaceWrapper) GenerateName(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateName(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/v1alpha1/buckets", wrapper.ListBuckets)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/buckets", wrapper.CreateBucket)
	m.HandleFunc("GET "+options.BaseURL+"/v1alpha1/buckets/{id}", wrapper.GetBucketDetails)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1alpha1/buckets/{id}", wrapper.UpdateBucket)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/buckets/{id}/archive", wrapper.ArchiveBucket)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/buckets/{id}/pop", wrapper.PopBucketName)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/buckets/{id}/recover", wrapper.RecoverBucket)
	m.HandleFunc("POST "+options.BaseURL+"/v1alpha1/generate", wrapper.GenerateName)

	return m
}

type InternalServerErrorJSONResponse Error

type ListBucketsRequestObject struct {
	Params ListBucketsParams
}

type ListBucketsResponseObject interface {
	VisitListBucketsResponse(w http.ResponseWriter) error
}

type ListBuckets200JSONResponse struct {
	Buckets []BucketListItem `json:"buckets"`
}

func (response ListBuckets200JSONResponse) VisitListBucketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListBuckets500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListBuckets500JSONResponse) VisitListBucketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateBucketRequestObject struct {
	Body *CreateBucketJSONRequestBody
}

type CreateBucketResponseObject interface {
	VisitCreateBucketResponse(w http.ResponseWriter) error
}

type CreateBucket201Response struct {
}

func (response CreateBucket201Response) VisitCreateBucketResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreateBucket500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateBucket500JSONResponse) VisitCreateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBucketDetailsRequestObject struct {
	Id int32 `json:"id"`
}

type GetBucketDetailsResponseObject interface {
	VisitGetBucketDetailsResponse(w http.ResponseWriter) error
}

type GetBucketDetails200JSONResponse BucketDetails

func (response GetBucketDetails200JSONResponse) VisitGetBucketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBucketDetails500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetBucketDetails500JSONResponse) VisitGetBucketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBucketRequestObject struct {
	Id   int32 `json:"id"`
	Body *UpdateBucketJSONRequestBody
}

type UpdateBucketResponseObject interface {
	VisitUpdateBucketResponse(w http.ResponseWriter) error
}

type UpdateBucket200JSONResponse BucketDetails

func (response UpdateBucket200JSONResponse) VisitUpdateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBucket400JSONResponse ProblemDetail

func (response UpdateBucket400JSONResponse) VisitUpdateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBucket404JSONResponse ProblemDetail

func (response UpdateBucket404JSONResponse) VisitUpdateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBucket409JSONResponse ProblemDetail

func (response UpdateBucket409JSONResponse) VisitUpdateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBucket500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateBucket500JSONResponse) VisitUpdateBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ArchiveBucketRequestObject struct {
	Id int32 `json:"id"`
}

type ArchiveBucketResponseObject interface {
	VisitArchiveBucketResponse(w http.ResponseWriter) error
}

type ArchiveBucket200JSONResponse BucketDetails

func (response ArchiveBucket200JSONResponse) VisitArchiveBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ArchiveBucket404JSONResponse ProblemDetail

func (response ArchiveBucket404JSONResponse) VisitArchiveBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ArchiveBucket500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ArchiveBucket500JSONResponse) VisitArchiveBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PopBucketNameRequestObject struct {
	Id int32 `json:"id"`
}

type PopBucketNameResponseObject interface {
	VisitPopBucketNameResponse(w http.ResponseWriter) error
}

type PopBucketName200JSONResponse struct {
	// Name The popped server name
	Name string `json:"name"`
}

func (response PopBucketName200JSONResponse) VisitPopBucketNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PopBucketName409JSONResponse ProblemDetail

func (response PopBucketName409JSONResponse) VisitPopBucketNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PopBucketName500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PopBucketName500JSONResponse) VisitPopBucketNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RecoverBucketRequestObject struct {
	Id int32 `json:"id"`
}

type RecoverBucketResponseObject interface {
	VisitRecoverBucketResponse(w http.ResponseWriter) error
}

type RecoverBucket200JSONResponse BucketDetails

func (response RecoverBucket200JSONResponse) VisitRecoverBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RecoverBucket404JSONResponse ProblemDetail

func (response RecoverBucket404JSONResponse) VisitRecoverBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RecoverBucket500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RecoverBucket500JSONResponse) VisitRecoverBucketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GenerateNameRequestObject struct {
	Body *GenerateNameJSONRequestBody
}

type GenerateNameResponseObject interface {
	VisitGenerateNameResponse(w http.ResponseWriter) error
}

type GenerateName200JSONResponse struct {
	// Name The generated server name
	Name string `json:"name"`
}

func (response GenerateName200JSONResponse) VisitGenerateNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateName400JSONResponse ProblemDetail

func (response GenerateName400JSONResponse) VisitGenerateNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateName500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GenerateName500JSONResponse) VisitGenerateNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all buckets
	// (GET /v1alpha1/buckets)
	ListBuckets(ctx context.Context, request ListBucketsRequestObject) (ListBucketsResponseObject, error)
	// Create a new bucket
	// (POST /v1alpha1/buckets)
	CreateBucket(ctx context.Context, request CreateBucketRequestObject) (CreateBucketResponseObject, error)
	// Get bucket details
	// (GET /v1alpha1/buckets/{id})
	GetBucketDetails(ctx context.Context, request GetBucketDetailsRequestObject) (GetBucketDetailsResponseObject, error)
	// Update bucket
	// (PATCH /v1alpha1/buckets/{id})
	UpdateBucket(ctx context.Context, request UpdateBucketRequestObject) (UpdateBucketResponseObject, error)
	// Archive a bucket
	// (POST /v1alpha1/buckets/{id}/archive)
	ArchiveBucket(ctx context.Context, request ArchiveBucketRequestObject) (ArchiveBucketResponseObject, error)
	// Pop a name from bucket
	// (POST /v1alpha1/buckets/{id}/pop)
	PopBucketName(ctx context.Context, request PopBucketNameRequestObject) (PopBucketNameResponseObject, error)
	// Recover an archived bucket
	// (POST /v1alpha1/buckets/{id}/recover)
	RecoverBucket(ctx context.Context, request RecoverBucketRequestObject) (RecoverBucketResponseObject, error)
	// Generate a random server name
	// (POST /v1alpha1/generate)
	GenerateName(ctx context.Context, request GenerateNameRequestObject) (GenerateNameResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBuckets operation middleware
func (sh *strictHandler) ListBuckets(w http.ResponseWriter, r *http.Request, params ListBucketsParams) {
	var request ListBucketsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBuckets(ctx, request.(ListBucketsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBuckets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBucketsResponseObject); ok {
		if err := validResponse.VisitListBucketsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBucket operation middleware
func (sh *strictHandler) CreateBucket(w http.ResponseWriter, r *http.Request) {
	var request CreateBucketRequestObject

	var body CreateBucketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBucket(ctx, request.(CreateBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBucket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBucketResponseObject); ok {
		if err := validResponse.VisitCreateBucketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBucketDetails operation middleware
func (sh *strictHandler) GetBucketDetails(w http.ResponseWriter, r *http.Request, id int32) {
	var request GetBucketDetailsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBucketDetails(ctx, request.(GetBucketDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBucketDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBucketDetailsResponseObject); ok {
		if err := validResponse.VisitGetBucketDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateBucket operation middleware
func (sh *strictHandler) UpdateBucket(w http.ResponseWriter, r *http.Request, id int32) {
	var request UpdateBucketRequestObject

	request.Id = id

	var body UpdateBucketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBucket(ctx, request.(UpdateBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBucket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateBucketResponseObject); ok {
		if err := validResponse.VisitUpdateBucketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ArchiveBucket operation middleware
func (sh *strictHandler) ArchiveBucket(w http.ResponseWriter, r *http.Request, id int32) {
	var request ArchiveBucketRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ArchiveBucket(ctx, request.(ArchiveBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ArchiveBucket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ArchiveBucketResponseObject); ok {
		if err := validResponse.VisitArchiveBucketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PopBucketName operation middleware
func (sh *strictHandler) PopBucketName(w http.ResponseWriter, r *http.Request, id int32) {
	var request PopBucketNameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PopBucketName(ctx, request.(PopBucketNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PopBucketName")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PopBucketNameResponseObject); ok {
		if err := validResponse.VisitPopBucketNameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecoverBucket operation middleware
func (sh *strictHandler) RecoverBucket(w http.ResponseWriter, r *http.Request, id int32) {
	var request RecoverBucketRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecoverBucket(ctx, request.(RecoverBucketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecoverBucket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecoverBucketResponseObject); ok {
		if err := validResponse.VisitRecoverBucketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateName operation middleware
func (sh *strictHandler) GenerateName(w http.ResponseWriter, r *http.Request) {
	var request GenerateNameRequestObject

	var body GenerateNameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateName(ctx, request.(GenerateNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateName")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateNameResponseObject); ok {
		if err := validResponse.VisitGenerateNameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbW8UOfL/KiX//y/YU89DQriFeRdg4SIBF4VwJx1CyNNdPePFbTe2e8IIzXc/le3u",
	"6adk2CUL2T2kvJhMu6vKVb/61cN8ZqkuSq1QOcsWn5lBW2pl0f9zphwaxeVrNBs0vxijDX2dauVQOfrI",
	"y1KKlDuh1exXqxV9Z9M1Fpw+/b/BnC3Y/832OmbhqZ0FabvdLmEZ2tSIkoSwRaMUrNcKGA8mUbC37HGV",
	"fkD3FB0X0n9RGl2icSIYzk26FhvM3nNvZVfBpSjQOl6UcLVGBW6NsPTi4IpbqF9lCcu1KUgAy7jDiRMF",
	"soSpSkq+lMgWzlSYMLctkS2YdUaoFdslLDXI3e9SHd9kCcNPvChJBzueHz+YHB1Pjo8vj+aLOf395zrT",
	"BqZ0lPdtebr/D3TesqWjP4QeFC/QQq4NlEZnVerfQrURRquCsDCiPRfSobFDzc/8A0i1ysWqMh49XrZb",
	"C7s3ohtSiWrl1kNhL/z3JMw6w4VysOGyQrhHgQKRg9IOUFHIsp/aVzs6uTaYQjlcoaFLBLXvo4Ch+n+v",
	"0a3RQDgH4c5CrUDYWmtbaUfNUmuJXLXUFDrDoY6XOkPvH9m/K4lWVcEWb1lVOh00pU5u2bt2EOOzXoR2",
	"CTP4sRKG7vW2f9N3zXm9/BVTR1aKEQe8UeJjhSAyVE7kAk2M5BiajlrAFcrdP2ZjLiesDfW84gXegNM9",
	"LCeBN+wYJA0WXCihVu9LLsag+aoqlmhIT0B88wIIdY3qk+Purf5+Mnqrqsx+Jy1Ibh3E12/ghvs3csMB",
	"2uphQZAiH4cuiXTYbejOfc6PoSdw9gth3ZnD4gdp30nS/tOn+F8vz8ZyqenFuikkYu809U3TtEBr+WrE",
	"002P5c9BPAf3tJJbYroMl9UKqBp1SibdlC+5RSpBCgOgci5CkRtiqWtNeH7AFDp02I6/+cM2CH4dFI4Y",
	"4ISTIyp/CZr8w7bUxpSYP8HJh2IY5IwF6dzopcQidKlDMy6ePYGfH85/hngOYjvrs+sfl5fncHp+ZgeN",
	"UHaNuFNYVwVXE4M8IwQCfiolV6G7siWmIhcpOB26LJ2mlTGo0q4LLtcIdDm0jmLsuFAWhNpwKTIgpAhr",
	"qRrWDoBcoMxGE9E67qqREutvFh5CSv1OS/+DR4/G6OKaOJ6CXWvjkv7FbVUU3GxrKimDe3uhDlcSqqwc",
	"ndiIbBzE46g9hTcXZ2AwR+9DcGvu9gRp23o9pDvK46f3+EX4in6Mx5Jr8bbzGZfrEWPPzzymVqiQum2K",
	"H1eZLuoRKxQKrjIouOIrOkBfRXK0jdJI0S+3dYacnp+xhBEVB01H0/l0PuGyXPMjcp4uUfFSsAW7P51P",
	"7xOWuVt7UMw2R+HcrNay+MxWOMLaF+gqoyxwkMI6iiqXsrYtAe3PcSm3sfvGjFBu1/oKPI/UzUHrOpRP",
	"PjHOMhohhHWPm2clN7zAMLm8HbBVDqVBi8rBPYMrbjKJ1pJNfur4KQETrb1OtSAxHys025r6F6zVvuyH",
	"5z4q3iXd4fx4Pv9Nw3iXRVpOFw4Le2hc7zVvTWIwbgzfDkBbix+Hadenr6s0RWvzikJo0BmBe5f5mJO6",
	"B+G6YzY2bpmNLSz85iAwQox1Gz8kutR2BHZPfAUm2Cm8qq2hHMmFlBaEgyvh1nVSYRaziMpjBlrVFOCJ",
	"Beq+uA+9oORx3exE6n2ss+1XxPaOjv3/jIlaO8PL9TxTE5NWUzgLE3vtuaQmJ4MtV5PndeVak7CdfsXG",
	"oEWOTRzvNSVO5NCdjWm2p+5usE74svVBzivp2CLn0mLyjdYJUWe9CfhW+4VBS/SHNf49/vF6xslnf4y8",
	"txuw6tHQvpCfYNtEVc99t0dNgQs6fONPDCrl7LPIdgfLZegTCa0qTCqUu3xJacP3/WDj7i4vPUfXXbEe",
	"qIvRQ2dP6wpHdX5f4Pyc03V8u9QdnBi/uvgdLm31RX9zgcrqF28NCM/RjQgvuUtH2OyNH1gtFJXzzW9o",
	"yH2XFIVM4Ylv9Z3chq6E0qwlBFKuYIn16DsFSsekZunE17y0MlYbz8KiiKqmA9QEW5pq9v0R84dX01d4",
	"1XFldzEyhTcWAYvSbSEQFXWmqURu+kGYdhgvODLr9uc3luGCf3oR693x/OThF5Dxl3Dh90qyCMWGBRN2",
	"cou2dOfyEVse8wwu4hQ8gX/RpMjbuw5vz8m3s+eVdvBMVyqDCcS8yTTa8NPGp9ggn8wffTuLnmiVS5G6",
	"vUFiv4X1jEHT+ITo5haJMaTF4do4i5b4ZB5t7l9y88E2DAmtFfIUTntDm2e95jr+cleCJggEXjlNlTX1",
	"42eGEgm1PHdo4D5kfGuncOnXLTVPkp9EhkWpKUowiXqJGrgCLknPdtKbG5uhMnYgQ+aNNt8h6r0TPNLz",
	"491M3FtKjgiBBtQ35Uepy+tz4wILvYn7INPsXvyglhtd+MoV+8e9Z/uAPNdluPCrsN3+UwOy2xCMzzCX",
	"NO7rsuxW7U5VXxq+wUmhK79X/ZoZ5gbIRxv6AWsnwF++TpzrsuOAwwlhMNUbNIeTgnzZ2B+32F5HnXYJ",
	"FPyDn9gd8NT5jFxxoQ4WgmhCvxIEEV9aBy6CkB91oD+0ebf8bxSCiAGPon7962RAvfK6HvXP4wkqAFao",
	"lcSRXw7CHlT3tnsjK4UgKxaE2xnOfiwbfywbr5tvRyrn7hs1Avv4ftdeYG9GqIbfeZCuf3QNQIN9bQLK",
	"TQ0Fd+kab3eTFhwAfIS3gsH1RnlYHl/olEvIcINSlwUV6XCWJawyki3Y2rlyMZtJOrfW1i0ezh/OZ7wU",
	"bPdu998AAAD//6ihZ3RZKwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
